version: "3"

services:
  simpleapp:
    image: simpleapp:latest
    build: 
      context: .
    working_dir: /var/app
    env_file: .env
    container_name: simpleapp
    networks:
      - app_net
    volumes:
      - ./app:/var/app/
    command: ["gunicorn", "app:create_app()", "-c/var/gunicorn.conf.py"]
    ports:
     - "5000:5000"
networks:
  app_net:

