version: "3"

services:
  app:
    image: app:latest
    build:
      context: .
    working_dir: /var/app
    env_file: .env
    container_name: app
    networks:
      - app_net
    volumes:
      - ./app:/var/app/
      - ./tests:/var/app/tests
    command:
      [
        "gunicorn",
        "app:create_app()",
        "-c/var/gunicorn.conf.py"
      ]
    ports:
      - "80:5000"
networks:
  app_net:
    name: app_net
    external: True
